### PR TITLE
Update pcfmetrics_ki_1_6.html.md.erb

### PR DESCRIPTION
**Pull request by AmberAlston**
Noticed these PCF 1.6 specific set of docs was now 2 versions behind with today's Metrics 1.0.14 bump and also 1.0.11 is mistakenly referencing 1.1 known issues not 1.0 known issues. Corrected 1.0.11 content mistake and also added updates for recently released 1.0.13 and new 1.0.14

### CODE REVIEW

**Comment by sleslie23** [comment]
Thanks @AmberAlston !!!

**Comment by bentarnoff** [comment]
Hey @AmberAlston I noticed that you just pushed a commit this closed PR, but I think there are conflicts. Could you open a new PR against `1.6`?

**Comment by AmberAlston** [comment]
@bentarnoff thanks for bringing that to my attention. I made a new PR here https://github.com/pivotal-cf/pcf-release-notes/pull/45.

**Comment by bentarnoff** [comment]
@AmberAlston Thanks. Closing.

**Pull request closed without merging**
