### PR TITLE
Add smb mapping feature for windows 2.3

### PR DESCRIPTION
**Pull request by genevieve**
https://www.pivotaltracker.com/story/show/161191411

@natalieparellano @micahyoung

### CODE REVIEW

**Comment by vikafed** [comment]
Hi @genevieve. Should we add this information only to 2.3? Or should we port it to 2.2 and 2.1 as well?

**Comment by genevieve** [comment]
@micahyoung ^

**Comment by vikafed** [comment]
Another question about this. In the 2.4 Release Notes, we documented this feature as Beta: https://docs.pivotal.io/pivotalcf/2-4/pcf-release-notes/windows-rn.html#smb. Do we need do modify the 2.4 note? It's no longer Beta, correct?

**Comment by vikafed** [comment]
@genevieve, could you take a look at the question above?

**Comment by micahyoung** [comment]
Hello @vikafed, Sorry for the wait. We should add this only for 2.3 and above (the code changes are yet to be done for 2.2 and 2.1) : 

I updated the copy below to reflect the current state of things. Does this look ok?
```
## SMB Mapping Support for Windows Containers

SMB mapping allows developers to bind existing SMB shares to their containerized apps. Previously, SMB shares were only accessible by using the SharpCIFS library. PASW v2.4.0 natively supports SMB mounting.

This enables usage of the net use command. This is currently limited to Fully Qualified Domain Name or IP address-based UNC paths.

For more information, see SMB (WINDOWS) FILE SHARES in the .NET on Pivotal Cloud Foundry cookbook.
```

**Comment by vikafed** [comment]
Thanks @micahyoung. Is there any difference between the 2.3 and 2.4 version of this feature? If they are identical, we'll need only one release note that will be published in the 2.3 docs. We can re-use the language you suggested here, replacing 2.4 with 2.3.

**Pull request merged**
